// Autogenerated, do not edit!
#include <component//core.hpp>
#include <million/engine.hpp>

using namespace entt::literals;

namespace init_core {

    void register_components (gou::api::Engine* engine)
    {
        entt::registry& registry = engine->registry(gou::api::Registry::Runtime);
		entt::registry& background_registry = engine->registry(gou::api::Registry::Background);
		entt::registry& prototype_registry = engine->registry(gou::api::Registry::Prototype);

        
    }

} // init_core

